"use strict";

const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const test = require("node:test");

test("channels support categories and roles enforce hierarchy", () => {
  const root = path.join(__dirname, "..");
  const schema = fs.readFileSync(path.join(root, "schema.sql"), "utf8");
  const api = fs.readFileSync(path.join(root, "src", "api.js"), "utf8");
  const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  const cleanCss = fs.readFileSync(path.join(root, "clean.css"), "utf8");

  assert.match(schema, /CREATE TABLE IF NOT EXISTS channel_categories/);
  assert.match(schema, /category_id UUID/);
  assert.match(schema, /role_icon TEXT/);
  assert.match(schema, /role_hoist BOOLEAN/);
  assert.match(api, /highestRolePosition/);
  assert.match(api, /roleIconValue/);
  assert.match(api, /role_icon/);
  assert.match(api, /role_hoist/);
  assert.match(api, /Kendi rolüne eşit veya yüksek bir rolü yönetemezsin/);
  assert.match(api, /Bu rolü veremezsin/);
  assert.match(app, /channel-category-input/);
  assert.match(app, /category-form/);
  assert.match(app, /serverIconMarkup/);
  assert.match(app, /await loadServers\(serverId\)/);
  assert.match(app, /resizeServerLogoFile/);
  assert.match(app, /saveActiveServerLogo/);
  assert.match(app, /Sunucu logosu kaydedildi/);
  assert.match(app, /function roleIcon/);
  assert.match(app, /role_hoist/);
  assert.match(app, /profile-role-tools/);
  assert.match(app, /roleIcon: \$\("#role-icon-input"\)/);
  assert.match(app, /roleHoist: \$\("#role-hoist-input"\)\.checked/);
  assert.doesNotMatch(app, /event\.currentTarget\.reset\(\)/);
  assert.match(api, /SERVER_TEMPLATES/);
  assert.match(api, /leaveServerRoute/);
  assert.match(html, /data-server-template="gaming"/);
  assert.match(html, /data-settings-panel="overview"/);
  assert.match(html, /settings-server-logo-url-input/);
  assert.match(html, /settings-server-logo-url-input" maxlength="350000"/);
  assert.match(html, /role-icon-input/);
  assert.match(html, /role-hoist-input/);
  assert.match(html, /profile-role-select/);
  assert.match(cleanCss, /settings-panel\[data-settings-panel="roles"\]/);
  assert.match(cleanCss, /role-icon-badge/);
  assert.match(cleanCss, /role-hoist-switch/);
  assert.match(cleanCss, /\.voice-dock/);
  assert.match(cleanCss, /\.server-logo/);
});
