"use strict";

const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const test = require("node:test");

test("server deletion is owner-only and friends can use direct messages", () => {
  const root = path.join(__dirname, "..");
  const schema = fs.readFileSync(path.join(root, "schema.sql"), "utf8");
  const database = fs.readFileSync(path.join(root, "src", "database.js"), "utf8");
  const api = fs.readFileSync(path.join(root, "src", "api.js"), "utf8");
  const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
  const cleanCss = fs.readFileSync(path.join(root, "clean.css"), "utf8");

  assert.match(schema, /CREATE TABLE IF NOT EXISTS friendships/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS direct_messages/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS message_requests/);
  assert.match(database, /CREATE TABLE IF NOT EXISTS friendships/);
  assert.match(database, /CREATE TABLE IF NOT EXISTS message_requests/);
  assert.match(api, /sunucu sahibi/);
  assert.match(api, /message_requests/);
  assert.match(api, /\/api\/message-requests/);
  assert.match(app, /delete-server-button/);
  assert.match(app, /friend-request-form/);
  assert.match(app, /dm-message-form/);
  assert.match(app, /closeDmThread/);
  assert.match(app, /openMessengerPage/);
  assert.match(app, /loadMessageRequests/);
  assert.match(app, /formatMessageContent/);
  assert.match(app, /updateMentionSuggestions/);
  assert.match(app, /activeDmTab/);
  assert.match(app, /renderDmTabContent/);
  assert.match(app, /notificationRows/);
  assert.match(app, /const showContactActions = true/);
  assert.match(app, /mediaFeatureAvailable/);
  assert.match(app, /yaas:ui-version/);
  assert.doesNotMatch(app, /server-dm-setting"\]/);
  assert.match(app, /channel-template-item/);
  assert.match(app, /role-template-card/);
  assert.match(html, /id="dm-back-button"/);
  assert.match(html, /mention-suggestions/);
  assert.match(html, /id="message-request-list"/);
  assert.match(html, /id="dm-notification-list"/);
  assert.match(html, /messenger-quick-tabs/);
  assert.match(html, /data-dm-tab="friends"/);
  assert.match(html, /data-dm-tab="requests"/);
  assert.match(html, /data-dm-tab="notifications"/);
  assert.match(html, /dm-tab-content/);
  assert.match(html, /messenger-page/);
  assert.match(html, /clean\.css/);
  assert.match(html, /data-dm-emoji/);
  assert.match(css, /\.dm-emoji-bar/);
  assert.match(css, /\.messenger-layer/);
  assert.match(css, /\.messenger-page/);
  assert.match(css, /\.messenger-quick-tabs/);
  assert.match(css, /\.channel-template-item/);
  assert.match(css, /\.role-template-card/);
  assert.match(cleanCss, /YAAS clean layout pass/);
  assert.match(cleanCss, /\.server-actions/);
  assert.match(cleanCss, /\.channel-template-item/);
  assert.match(cleanCss, /\.messenger-page \.friends-layout/);
  assert.match(cleanCss, /\.messenger-page \.friend-section/);
  assert.match(cleanCss, /\.dm-tab-content/);
  assert.match(cleanCss, /\.mention-suggestions/);
  assert.match(cleanCss, /#server-dm-setting/);
  assert.match(css, /\.friends-modal\.dm-open/);
});
